### ISSUE TITLE
selenium

### ISSUE THREAD

**Issue by brunobell** [creatorYC/v2ex-terminal#2]
hi, do you have any plans to replace selenium calls with requests? I reckon that as a terminal program you should use as little requirements as possible just as the terminal does. Anyway it's a nice project!

**Comment by ye-yechen** [comment]
@brunobell In this project I used the selenium for the first time,I learnt a little about selenium.In fact,I have listened something about the "headless chrome", I want to try this headless chrome,but unfortunately,the headless chrome have not been supported on Windows.So finally as you can see now,I have add this "search" function through these ugly codes.Maybe I will replace selenium with requests,thanks for your advice.
